# Generated by Django 2.1.7 on 2019-08-04 12:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0002_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='message',
            new_name='question',
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('user', 'question')},
        ),
    ]
