# Generated by Django 2.1.7 on 2019-08-08 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_remove_answer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='accepted_answer',
            field=models.OneToOneField(null=True, on_delete=None, related_name='question_accepting', to='questions.Answer'),
        ),
    ]
