# Generated by Django 2.1.7 on 2019-08-08 06:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0008_remove_question_approved_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=None, related_name='answers', to=settings.AUTH_USER_MODEL),
        ),
    ]
