# Generated by Django 2.1.7 on 2019-08-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_answer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='user',
        ),
        migrations.AddField(
            model_name='answer',
            name='author',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
