# Generated by Django 2.1.7 on 2019-08-10 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_auto_20190808_1224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-hit_count_generic__hits']},
        ),
    ]
